# Generated by Django 5.0 on 2023-12-08 07:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("webapp", "0002_review_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="deleted_at",
            field=models.DateTimeField(
                default=None, null=True, verbose_name="Дата и время удаления"
            ),
        ),
        migrations.AddField(
            model_name="book",
            name="is_deleted",
            field=models.BooleanField(default=False, verbose_name="удалено"),
        ),
    ]
