# Generated by Django 5.0 on 2023-12-10 20:26

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("webapp", "0004_book_average_rating"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="favoritebook",
            unique_together={("user", "book")},
        ),
    ]
